export const SAMPLE_ACTION = 'SAMPLE_ACTION';

export const FETCH_FLICKR_BEGIN = 'FETCH_FLICKR_BEGIN';
export const FETCH_FLICKR_SUCCESS = 'FETCH_FLICKR_SUCCESS';
export const FETCH_FLICKR_FAILURE = 'FETCH_FLICKR_FAILURE';
export const FETCH_FLICKR_DISMISS_ERROR = 'FETCH_FLICKR_DISMISS_ERROR';